Api dissertation
uclouvain/osis-dissertation pull request #113
Opened 2022-05-19 08:58 UTC by chfivet

Référence Jira : OSIS-

Vérifier les points suivants : 
- [ ] Ouvrir une release task Jira si le ticket génère une tâche pour la release : 
    - modification de configuration
    - table à synchroniser en entier, etc.
- [ ] Uniformiser les modèles osis-portal avec les changements effectués dans osis si nécessaire
- [ ] Permissions et droits d’accès mettre à jour la documentation si : 
    - on rajoute/modifie une permission
    - on rajoute/modifie un groupe d’utilisateurs, etc.

2022-05-19 12:31 UTC, albrugnetti requested changes

2022-05-19 12:31 UTC, albrugnetti commented on schema.yml
> +          description: 'The resource was updated successfully.'
La ressource a été soumise

2022-05-19 12:31 UTC, albrugnetti commented on schema.yml
> +          description: 'The resource was updated successfully.'
Idem

2022-05-19 12:31 UTC, albrugnetti commented on schema.yml
> +          example: "f8b61488-f32b-4382-8633-3bf81fc5d6a5"
A enlever car déjà déclaré dans l'URL

2022-05-25 12:24 UTC, chfivet commented on schema.yml
> +          description: 'The resource was updated successfully.'
Done

2022-05-25 12:24 UTC, chfivet commented on schema.yml
> +    DissertationSubmit:
Done

2022-05-25 12:25 UTC, chfivet commented on schema.yml
> +    DissertationBackToDraft:
Done

2022-05-25 12:25 UTC, chfivet commented on schema.yml
> +          example: "f8b61488-f32b-4382-8633-3bf81fc5d6a5"
Done

2022-05-25 12:25 UTC, chfivet commented on schema.yml
> +          example: "f8b61488-f32b-4382-8633-3bf81fc5d6a5"
Done

2022-07-08 14:32 UTC, chfivet commented on api/views/proposition_dissertation.py
> +        ]
Done

2022-07-11 06:41 UTC, BenJneB commented on api/serializers/adviser.py
> +#    Copyright (C) 2015-2021 Université catholique de Louvain (http://www.uclouvain.be)
2022

2022-07-11 07:52 UTC, chfivet commented on api/serializers/adviser.py
> +#    Copyright (C) 2015-2021 Université catholique de Louvain (http://www.uclouvain.be)
Done

2022-07-11 08:49 UTC, chfivet commented on api/views/dissertation.py
> +        return OfferProposition.objects.get(
Done ça passe

2022-07-11 09:11 UTC, chfivet commented on api/views/proposition_dissertation.py
> +            offer_propositions__in=self.offer_propositions_ids
Done

2022-07-12 09:34 UTC, BenJneB commented on api/views/proposition_dissertation.py
> +        return PropositionDissertation.objects.select_related('author__person').prefetch_related(prefetch_propositions)
Plus besoin des filtre active et visibilty ??

2022-07-12 09:34 UTC, BenJneB commented on models/dissertation.py
> +    return 'dissertation/{}/{}'.format(dissertation.uuid, filename)
f"dissertation/{dissertation.uuid}/{filename}"
f-string

2022-07-12 09:34 UTC, BenJneB commented on models/proposition_dissertation.py
> +    return 'proposition_dissertation/{}/{}'.format(proposition_dissertation.uuid, filename)
f-string

2022-07-12 09:34 UTC, BenJneB commented on views/dissertation.py
> +    )
```python3
dissertation_file_form = DissertationFileForm(
    request.POST or None,
    instance=dissert
)
if request.method == 'POST' and dissertation_file_form.is_valid():
    dissertation_file_form.save()
    return redirect(...)
proposition_dissertation_file_form = PropositionDissertationFileForm(
    instance=dissert.proposition_dissertation
)
```

2022-07-12 09:34 UTC, BenJneB commented on views/dissertation.py
> +                     'proposition_dissertation__author__person').distinct()
indentation

2022-07-12 09:34 UTC, BenJneB commented on views/dissertation.py
>          active=True).filter(
indentation

2022-07-12 09:34 UTC, BenJneB commented on views/dissertation.py
> +                       })
indentation

2022-07-12 09:34 UTC, BenJneB commented on views/proposition_dissertation.py
> +        )
même proposition que plus tôt

2022-07-12 09:34 UTC, BenJneB commented on views/proposition_dissertation.py
> +        proposition
idem

2022-07-12 12:42 UTC, chfivet commented on api/url_v1.py
> +            include(([
Yep DOne

2022-07-12 12:45 UTC, chfivet commented on api/views/proposition_dissertation.py
> +        return PropositionDissertation.objects.select_related('author__person').prefetch_related(prefetch_propositions)
erreur lors du refactoring merci

2022-07-12 12:47 UTC, chfivet commented on models/dissertation.py
> +    return 'dissertation/{}/{}'.format(dissertation.uuid, filename)
Yep si c'est plus propre pourquoi pas

2022-07-12 12:48 UTC, chfivet commented on views/dissertation.py
> +    )
Done

2022-07-12 12:54 UTC, chfivet commented on templatetags/dissertation.py
> +def field_data(name, data=None):
Ils doivent le récupérer sur OSIS-DOCUMENT mais je l'ai viré du tempalte pour passer par défaut "" dans le templatetags

2022-07-12 13:02 UTC, BenJneB commented on views/proposition_dissertation.py
> +        return redirect(...)
Non mais pas les ... 
c'était pour m'éviter de recopier xD
`return redirect('proposition_dissertation_detail', pk=proposition.pk)`

2022-07-12 13:04 UTC, chfivet commented on views/proposition_dissertation.py
> +        return redirect(...)
A merde sorry j'ai pas fait gaffe je fxed ça

2022-07-12 13:06 UTC, BenJneB approved these changes

2022-09-02 09:22 UTC, closed without merging