[OSIS-9160] Dissertation Migration BS5
uclouvain/osis-dissertation pull request #151
Opened 2024-06-11 14:32 UTC by leboiss

Référence Jira : OSIS-9160
Cette Pr est lié à la PR suivante

2024-06-14 10:00 UTC, mdartic requested changes
Deux points à noter principalement : 
* chargement d'un fichier JS non minifié ?
* traduction qui me paraît être en ano dans certains cas (ptet un search & replace trop violent)

2024-09-04 09:20 UTC, mdartic commented
@leboiss up ?

2024-09-05 08:49 UTC, leboiss commented
> @leboiss up ?

J'ai ajouté le fichier dataTable.bootstrap5.min.js il est dans cette PR 
https://github.com/uclouvain/osis/pull/16653

Concernant les traductions il n'y a pas d'anomalies, sur certaines pages il y a avait marqué "Afficher" devant un select pour définir combien d'éléments on souhaite afficher mais il n'était pas présent sur d'autres pages, j'ai uniformisé les pages en enlevant ce texte

2024-11-05 15:49 UTC, mathieuzen approved these changes

2025-01-16 10:28 UTC, mathieuzen commented
rerun unit tests

2025-01-16 10:48 UTC, chfivet commented
rerun unit tests

2025-01-16 13:08 UTC, merged